- name: "Executing Install for {{ ansible_os_family + ' using v' + agent_client_collector_version }}"
  when: ansible_os_family in ['RedHat', 'Debian', 'Windows']
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: "Post Installation"
  ansible.builtin.include_tasks: "post_{{ ansible_system }}.yml"
