dependency:
  name: "galaxy"
driver:
  name: "docker"
provisioner:
  name: "ansible"
  # env:
  #   ANSIBLE_ROLES_PATH: "../../../roles"
  #   ANSIBLE_COLLECTIONS_PATH: "../../../../"
verifier:
  name: "ansible"
platforms:
  - name: "oraclelinux-9"
    image: "docker.io/dokken/oraclelinux-9"
    privileged: true
    command: "/usr/lib/systemd/systemd"
    buildargs:
      platform: "linux/amd64"
