namespace: "irunasroot"
name: "servicenow"
version: "1.1.0"
readme: "README.md"
authors:
  - "Dennis Whitney (https://github.com/minsis)"
description: "Ansible collection of various roles, plugins, modules, etc that help manage ServiceNow"
license_file: "LICENSE.txt"
tags:
  - "snow"
  - "servicenow"
  - "acc"
repository: "https://github.com/irunasroot/servicenow"
documentation: "https://github.com/irunasroot/servicenow/wiki"
homepage: "https://github.com/irunasroot/servicenow"
issues: "https://github.com/irunasroot/servicenow/issues"
build_ignore:
  - ".idea"
  - ".vscode"
  - ".gitignore"
  - ".yamllit"
  - "molecule"
  - "docs"
