dependency:
  name: "galaxy"

driver:
  name: "default"
  options:
    managed: true
    ansible_connection_options:
      ansible_connection: local

provisioner:
  name: "ansible"

verifier:
  name: "ansible"

platforms:
  - name: "local"
