dependency:
  name: "galaxy"
driver:
  name: "docker"
provisioner:
  name: "ansible"
verifier:
  name: "ansible"
platforms:
  - name: "oraclelinux-7"
    image: "docker.io/dokken/oraclelinux-7"
    privileged: true
    command: "/usr/lib/systemd/systemd"
