- name: "Installing Agent"
  win_package:
    path: "{{ agent_client_collector.download_uri }}"
    state: "present"
    product_id: "{{ agent_client_collector.revision }}"
    arguments: "/quiet ACC_MID='' ACC_API_KEY=''"
