force_uninstall_on_upgrade: true
restart_agent_after_config_changes: true

agent_client_collector:
  version: "2.7.0"
  revision: ""
  installation_path: ""

acc_configuration:
  name: "{{ ansible_fqdn }}"
  backend_url: []
  api_key: ""
  agent_key_id: ""
  log_level: "info"
  skip_tls_verify: "true"
  allow_list: "{{ check_allow_list_json_file_path }}"

  redact:
    - "username"
    - "bearer_token"
    - "auth_algorithm"
    - "access_key"
    - "enrollment_number"
    - "auth_method"
    - "client_id"
    - "ea_credential"
    - "certificate"
    - "cert_alias"
    - "secret_key"
    - "password"
    - "passwd"
    - "pass"
    - "api_key"
    - "api_token"
    - "private_key"
    - "secret"
    - "ssh_private_key"
    - "ssh_passphrase"
    - "authentication_key"
    - "authentication_protocol"
    - "privacy_key"
    - "privacy_protocol"

  verify_plugin_signature: "true"
  max_running_checks: 10

  agent_cpu_threshold:
    cpu_percentage_limit: 5
    repeated_high_cpu_num: 3
    monitor_interval_sec: 60
    agent_cpu_threshold_disabled: "false"
    proxy_cpu_percentage_limit: 15

  disable_sockets: "true"
  statsd_disable: "true"
  check_commands_prefer_installed: "false"

  enable_auto_mid_selection: "true"

acc_check_allow_list:
  - exec: "check-cpu.rb"
    skip_arguments: "true"
  - exec: "check-disk-usage.rb"
    skip_arguments: "true"
  - exec: "check-head-redirect.rb"
    skip_arguments: "true"
  - exec: "check-kube-apiserver-available.rb"
    skip_arguments: "true"
  - exec: "check-kube-pods-restarting.rb"
    skip_arguments: "true"
  - exec: "check-kube-pods-running.rb"
    skip_arguments: "true"
  - exec: "check-kube-pods-runtime.rb"
    skip_arguments: "true"
  - exec: "check-kube-service-available.rb"
    skip_arguments: "true"
  - exec: "check-load.rb"
    skip_arguments: "true"
  - exec: "check-log-sudo.sh"
    skip_arguments: "true"
  - exec: "check-log.rb"
    skip_arguments: "true"
  - exec: "check-memcached-stats.rb"
    skip_arguments: "true"
  - exec: "check-memory-percent.rb"
    skip_arguments: "true"
  - exec: "check-mongodb-metric.rb"
    skip_arguments: "true"
  - exec: "check-mysql-alive.rb"
    skip_arguments: "true"
  - exec: "check-mysql-query-result-count.rb"
    skip_arguments: "true"
  - exec: "check-mysql-threads.rb"
    skip_arguments: "true"
  - exec: "check-nginx-status.rb"
    skip_arguments: "true"
  - exec: "check-oracle-alive.rb"
    skip_arguments: "true"
  - exec: "check-ping.rb"
    skip_arguments: "true"
  - exec: "check-ports.rb"
    skip_arguments: "true"
  - exec: "check-process.rb"
    skip_arguments: "true"
  - exec: "check-rabbitmq-alive.rb"
    skip_arguments: "true"
  - exec: "check-rabbitmq-messages.rb"
    skip_arguments: "true"
  - exec: "check-rabbitmq-node-usage.rb"
    skip_arguments: "true"
  - exec: "check-redis-info.rb"
    skip_arguments: "true"
  - exec: "check-redis-ping.rb"
    skip_arguments: "true"
  - exec: "check-snmp.rb"
    skip_arguments: "true"
  - exec: "check-swap-percent.rb"
    skip_arguments: "true"
  - exec: "check-threads-count.rb"
    skip_arguments: "true"
  - exec: "check_discover.rb"
    skip_arguments: "false"
  - exec: "cscript"
    args:
      - "check_ad.vbs //nologo"
    skip_arguments: "false"
  - exec: "endpoint_discovery.rb"
    skip_arguments: "true"
  - exec: "running_processes.rb"
    skip_arguments: "false"
  - exec: "tcp_connections.rb"
    skip_arguments: "false"
  - exec: "file_systems.rb"
    skip_arguments: "false"
  - exec: "network_adapters.rb"
    skip_arguments: "false"
  - exec: "serial_numbers.rb"
    skip_arguments: "false"
  - exec: "storage_devices.rb"
    skip_arguments: "false"
  - exec: "metrics-apache-graphite.rb"
    skip_arguments: "true"
  - exec: "metrics-cpu-pcnt-usage.rb"
    skip_arguments: "true"
  - exec: "metrics-cpu.rb"
    skip_arguments: "true"
  - exec: "metrics-curl.rb"
    skip_arguments: "true"
  - exec: "metrics-disk-capacity.rb"
    skip_arguments: "true"
  - exec: "metrics-disk-usage.rb"
    skip_arguments: "true"
  - exec: "metrics-disk.rb"
    skip_arguments: "true"
  - exec: "metrics-docker-info.rb"
    skip_arguments: "true"
  - exec: "metrics-docker-stats.rb"
    skip_arguments: "true"
  - exec: "metrics-jmx.rb"
    skip_arguments: "true"
  - exec: "metrics-k8s.rb"
    skip_arguments: "true"
  - exec: "metrics-load.rb"
    skip_arguments: "true"
  - exec: "metrics-memcached-graphite.rb"
    skip_arguments: "true"
  - exec: "metrics-memcached-socket-graphite.rb"
    skip_arguments: "true"
  - exec: "metrics-memory-percent.rb"
    skip_arguments: "true"
  - exec: "metrics-memory-vmstat.rb"
    skip_arguments: "true"
  - exec: "metrics-memory.rb"
    skip_arguments: "true"
  - exec: "metrics-mongodb.rb"
    skip_arguments: "true"
  - exec: "metrics-mysql-graphite.rb"
    skip_arguments: "true"
  - exec: "metrics-mysql-processes.rb"
    skip_arguments: "true"
  - exec: "metrics-mysql-query-result-count.rb"
    skip_arguments: "true"
  - exec: "metrics-nginx.rb"
    skip_arguments: "true"
  - exec: "metrics-oracle.rb"
    skip_arguments: "true"
  - exec: "metrics-ping.rb"
    skip_arguments: "true"
  - exec: "metrics-process-status.rb"
    skip_arguments: "true"
  - exec: "metrics-query-oracle.rb"
    skip_arguments: "true"
  - exec: "metrics-rabbitmq-exchange.rb"
    skip_arguments: "true"
  - exec: "metrics-rabbitmq-overview.rb"
    skip_arguments: "true"
  - exec: "metrics-rabbitmq-queue.rb"
    skip_arguments: "true"
  - exec: "metrics-redis-graphite.rb"
    skip_arguments: "true"
  - exec: "metrics-snmp-bulk-sn.rb"
    skip_arguments: "true"
  - exec: "metrics-snmp.rb"
    skip_arguments: "true"
  - exec: "osqueryi"
    args:
      - "--logger_min_status 1"
      - "--json"
      - "\"select network_name, last_connected, captive_portal FROM wifi_networks WHERE captive_portal=1\""
      - "\"select * from apps\""
      - "\"select * from etc_hosts\""
      - "\"select * from os_version\""
      - "\"select DISTINCT processes.name, listening_ports.port, processes.pid FROM listening_ports JOIN processes USING (pid) WHERE listening_ports.address = '0.0.0.0'\""
      - "\"select * from logged_in_users\""
      - "\"select * from uptime\""
      - "\"select name, path, pid FROM processes WHERE on_disk = 0\""
      - "\"select u.username, g.gid, g.groupname FROM users u JOIN user_groups ug USING (uid) JOIN groups g ON ug.gid = g.gid WHERE uid > 500\""
      - "\"select pid, name, uid, resident_size from processes order by resident_size desc limit 10\""
      - "\"select * from system_info\""
      - "\"select * from certificates\""
      - "\"select path, type, round((blocks_available * blocks_size *10e-10),2) as gigs_free from mounts where path='/'\""
      - "\"select * from chrome_extensions\""
      - "\"select name from kernel_info\""
    skip_arguments: "false"
  - exec: "read-file.rb"
    skip_arguments: "true"
  - exec: "rebootcount.sh"
    skip_arguments: "false"
  - exec: "Restart"
    args:
      - "agent"
    skip_arguments: "false"
  - exec: "winchecks"
    skip_arguments: "true"
  - exec: "acc"
    args:
      - "self-test"
      - "self-test debug"
      - "self-test verbose"
    skip_arguments: "false"
